# Copyright 2014 OpenStack Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""extra capability

Revision ID: 02e2f2186d98
Revises: 520c9976941c
Create Date: 2020-04-17 15:51:40.542459

"""

# revision identifiers, used by Alembic.
revision = '02e2f2186d98'
down_revision = '520c9976941c'

from itertools import chain
import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    op.create_table('extra_capabilities',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('resource_type', sa.String(255), nullable=False),
                    sa.Column('capability_name', sa.String(255),
                              nullable=False),
                    sa.Column('private', sa.Boolean, nullable=False,
                              server_default=sa.false()),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('resource_type', 'capability_name'))

    if op.get_bind().engine.name != 'sqlite':
        connection = op.get_bind()

        host_query = connection.execute("""
            SELECT DISTINCT "physical:host", capability_name
            FROM computehost_extra_capabilities;""")
        network_query = connection.execute("""
            SELECT DISTINCT "network", capability_name
            FROM networksegment_extra_capabilities;""")

        capability_values = [
            (str(uuid.uuid4()), resource_type, capability_name)
            for resource_type, capability_name
            in chain(host_query.fetchall(), network_query.fetchall())]

        if capability_values:
            insert = """
                INSERT INTO extra_capabilities
                (id, resource_type, capability_name)
                VALUES {};"""
            connection.execute(
                insert.format(', '.join(map(str, capability_values))))

        op.add_column('computehost_extra_capabilities',
                      sa.Column('capability_id', sa.String(length=255),
                                nullable=False))
        op.add_column('networksegment_extra_capabilities',
                      sa.Column('capability_id', sa.String(length=255),
                                nullable=False))

        connection.execute("""
            UPDATE computehost_extra_capabilities c
            LEFT JOIN extra_capabilities e
            ON e.capability_name = c.capability_name
            SET c.capability_id = e.id;""")
        connection.execute("""
            UPDATE networksegment_extra_capabilities n
            LEFT JOIN extra_capabilities e
            ON e.capability_name = n.capability_name
            SET n.capability_id = e.id;""")

        op.create_foreign_key('computehost_extra_capability_id_fk',
                              'computehost_extra_capabilities',
                              'extra_capabilities', ['capability_id'], ['id'])
        op.create_foreign_key('networksegment_extra_capability_id_fk',
                              'networksegment_extra_capabilities',
                              'extra_capabilities', ['capability_id'], ['id'])

        op.drop_column('computehost_extra_capabilities', 'capability_name')
        op.drop_column('networksegment_extra_capabilities', 'capability_name')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('networksegment_extra_capabilities',
                  sa.Column('capability_name', mysql.VARCHAR(length=64),
                            nullable=False))
    op.add_column('computehost_extra_capabilities',
                  sa.Column('capability_name', mysql.VARCHAR(length=64),
                            nullable=False))

    if op.get_bind().engine.name != 'sqlite':
        connection = op.get_bind()
        connection.execute("""
            UPDATE networksegment_extra_capabilities n
            LEFT JOIN extra_capabilities e
            ON e.id = n.capability_id
            SET n.capability_name = e.capability_name;""")

        connection.execute("""
            UPDATE computehost_extra_capabilities c
            LEFT JOIN extra_capabilities e
            ON e.id=c.capability_id
            SET c.capability_name = e.capability_name;""")

        op.drop_constraint('networksegment_extra_capability_id_fk',
                           'networksegment_extra_capabilities',
                           type_='foreignkey')
        op.drop_column('networksegment_extra_capabilities', 'capability_id')

        op.drop_constraint('computehost_extra_capability_id_fk',
                           'computehost_extra_capabilities',
                           type_='foreignkey')
        op.drop_column('computehost_extra_capabilities', 'capability_id')
        op.drop_table('extra_capabilities')
